import { eq } from "cypress/types/lodash"
import { LogInPage } from "./loginpage/loginpage"

const logInPage = new LogInPage()

describe('Add to cart test suite', () => {
    beforeEach(function () {
        logInPage.login()
    })
    it('Add one item to cart', ()=> {
        cy.get('div[class=inventory_item_name]')
            .first()
            .should('have.text', 'Sauce Labs Backpack')
        cy.get('div[class=inventory_item_price]')
            .first()
            .invoke('text')
            .should('eq', '$29.99')
        cy.get('button[id=add-to-cart-sauce-labs-backpack]')
            .click()
        cy.get('button[id=remove-sauce-labs-backpack]')
            .should('have.text', 'Remove')
        cy.get('.shopping_cart_link').click()
        cy.get('div[class=inventory_item_name]')
            .first()
            .should('have.text', 'Sauce Labs Backpack')
        cy.get('div[class=inventory_item_price]')
            .first()
            .invoke('text')
            .should('eq', '$29.99')
        cy.get('button[id=remove-sauce-labs-backpack]')
            .should('have.text', 'Remove')
        cy.get('button[id=continue-shopping]')
            .should('have.text', 'Continue Shopping')
        cy.get('button[id=checkout]')
            .should('have.text', 'Checkout')
        cy.get('span[class=shopping_cart_badge]')
            .invoke('text')
            .then(parseFloat)
            .should('eq', 1)
        cy.get('.cart_quantity')
            .invoke('text')
            .then(parseFloat)
            .should('eq', 1)
        cy.url().should('include', '/cart.html')
    })
})