import { eq } from "cypress/types/lodash"
import { LogInPage } from "./loginpage/loginpage"

const logInPage = new LogInPage()

describe('Checkout test suite', () => {
    beforeEach(function () {
        logInPage.login()
    })
    it('Checkout your items', ()=> {
        cy.get('div[class=inventory_item_name]')
            .first()
            .should('have.text', 'Sauce Labs Backpack')
        cy.get('div[class=inventory_item_price]')
            .first()
            .invoke('text')
            .should('eq', '$29.99')
        cy.get('button[id=add-to-cart-sauce-labs-backpack]')
            .click()
        cy.get('button[id=remove-sauce-labs-backpack]')
            .should('have.text', 'Remove')
        cy.get('.shopping_cart_link').click()
        cy.url().should('include', '/cart.html')
        cy.get('[data-test="checkout"]').click()
        cy.url().should('include', '/checkout-step-one.html')
        cy.get('.title')
            .should('have.text', 'Checkout: Your Information')
        cy.get('[data-test="firstName"]').type('Testfirstname')
        cy.get('[data-test="lastName"]').type('Testlastname')
        cy.get('[data-test="postalCode"]').type('te1st2')
        cy.get('[data-test="continue"]').click()
        cy.url().should('include', '/checkout-step-two.html')
        cy.get('.title')
            .should('have.text', 'Checkout: Overview')
        cy.get('div[class=inventory_item_name]')
            .first()
            .should('have.text', 'Sauce Labs Backpack')
        cy.get('div[class=inventory_item_price]')
            .first()
            .invoke('text')
            .should('eq', '$29.99')
        cy.get('[data-test="finish"]')
            .should('be.visible')
        cy.get('[data-test="cancel"]')
            .should('be.visible')
        cy.get('.summary_info > :nth-child(2)')
            .invoke('text')
            .should('match', /^SauceCard #[\d\d\d\d\d]/)
        cy.get('.summary_info > :nth-child(4)')
            .should('have.text', 'FREE PONY EXPRESS DELIVERY!')
        cy.get('.summary_info > :nth-child(5)')
            .should('have.text', 'Item total: $29.99')
        cy.get('.summary_info > :nth-child(6)')
            .should('have.text', 'Tax: $2.40')
        cy.get('.summary_info > :nth-child(7)')
            .should('have.text', 'Total: $32.39')
        cy.get('[data-test="finish"]').click()
        cy.url().should('include', '/checkout-complete.html')
        cy.get('.title')
            .should('have.text', 'Checkout: Complete!')
        cy.get('.pony_express')
            .should('be.visible')
        cy.get('[data-test="back-to-products"]')
            .should('be.visible')
        cy.get('.complete-header')
            .should('have.text', 'THANK YOU FOR YOUR ORDER')
        cy.get('.complete-text')
            .should('have.text', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
    })
})